spring:
  thymeleaf:
    check-template-location: true
    cache: false
    prefix: file:./src/main/resources/templates/
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/task_master_db?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
    username: ${db_username}
    password: ${db_password}
  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  sql:
    init:
      mode: never
      platform: mysql
  mvc:
    hiddenmethod:
      filter:
        enabled: true
mail:
  api:
    baseUrl: http://localhost:8081/api

cloudinary:
  cloud_name: ${cloudinary_cloud_name}
  api_key: ${cloudinary_api_key}
  api_secret: ${cloudinary_api_secret}

tasks:
  retention:
    period: P365D

